POST http://localhost:4000/form HTTP/1.1
content-type: application/json
{
    "OrderNo": "1234",
        "Name": "harshitha",
        "Address": "Mandya",
        "Tehsil": "moysore",
        "District": "tumkur",
        "PinCode": 572104,
        "State": "karnataka",
        "Whatsapp": 9448285578,
        "Contact": 7259279158,
        "CompanyName": "mims",
        "Order":[
            {"Details":"banana",
            "Qty":34,
            "Rate":2,
            "Amount":68},
            {"Details":"bana23",
            "Qty":34,
            "Rate":5,
            "Amount":23}
            
        ],
       
        "TotalAmt":68,
        "Advance":346,
        "DeliveryPlace":"Goa",
        "Deposit":{
            "Amount":45,
            "UIRNo":456,
            "Bank":"HDFC"
        },        
        "AcHolder":"Kamlesh",
        "AcNo":2355652,
        "IFSC":"443sit",
        "DealerName":"jon",
        "DealerContact":2356734563

}
###